apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: api-frontend
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/khala-1-tenant/api-frontend/api-frontend@sha256:6af28802fa4c9ae76be533c758fc3b6f3cc07e1863aee9c8154631a0aaec1671
        name: container-image
        resources: {}
status: {}
