apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: api-frontend
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/khala-1-tenant/api-frontend/api-frontend@sha256:650ff42c54336e21738cd060beb3bd3f0b6f5301046a06a480e469d6ef638286
        name: container-image
        resources: {}
status: {}
