apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: api-frontend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: api-frontend
    app.kubernetes.io/part-of: api-frontend
  name: api-frontendsedi
spec:
  port:
    targetPort: 8000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: api-frontend
    weight: 100
status: {}
