apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: api-frontend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: api-frontend
    app.kubernetes.io/part-of: api-frontend
  name: api-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: api-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: api-frontend
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/khala-1-tenant/api-frontend/api-frontend@sha256:650ff42c54336e21738cd060beb3bd3f0b6f5301046a06a480e469d6ef638286
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
