apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: api-frontend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: api-frontend
    app.kubernetes.io/part-of: api-frontend
  name: api-frontend
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: api-frontend
status:
  loadBalancer: {}
